name: Deploy website

# This workflow is triggered on pushes to the repository.
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    name: Deploy AdaEngine Website

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate static site
        run: swift run AdaEngineWebsite --deploy

      - name: Deploy to GitHub Pages
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: Output
          token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          repository-name: AdaEngine/adaengine.github.io
          single-commit: true
          force: true
