name: Deploy website

# This workflow is triggered on pushes to the repository.
on:
  push:
    branches: [ main ]

permissions:
  contents: write

env:
  DEPLOY_ACCESS_TOKEN: ${{ secrets.DEPLOY_ACCESS_TOKEN }}

jobs:
  build:
    name: Deploy AdaEngine Website

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      run: swift run AdaEngineWebsite --deploy
