name: Swift

# This workflow is triggered on pushes to the repository.
on:
  push:
    branches: [ main ]

env:
  DEPLOY_ACCESS_TOKEN: ${{ secrets.DEPLOY_ACCESS_TOKEN }}

jobs:
  build:
    name: Deploy Blog

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      run: swift run AdaEngineWebsite --deploy
