name: Deploy website

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy-website:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Generate static site
        run: swift run AdaEngineWebsite

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: Build
          token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          repository-name: AdaEngine/adaengine.github.io
          single-commit: true
          force: true
